version: "3.7"
services:
  coordinator:
    image: golang:1.13
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run cmd/coordinator/main.go --host=0.0.0.0
    ports:
      - "9090:9090"

  server:
    image: golang:1.13
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: ./bin/wait-for-it coordinator:9090 -- go run cmd/server/main.go --coordinatorURL=ws://coordinator:9090 --profilerPort=9081
    tty: true
    ports:
      - "9081:9081"
    depends_on:
      - coordinator
