version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run: make test

  lint:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run: GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: GO111MODULE=off go get -u golang.org/x/lint/golint
      - run: make lint
      - run: make lintci

workflows:
  build_and_test:
    jobs:
      - build
      - lint
